apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app2
  namespace: default
  labels:
    app: sample-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app2
  template:
    metadata:
      labels:
        app: sample-app2
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 81
